/**
 * WS9 Daemon — wire protocol types.
 *
 * Hand-typed counterpart to `packages/coding-agent/openapi.yaml`. The intent
 * is for these to be regenerated by `openapi-typescript-codegen` once we wire
 * codegen in CI — until then we hand-maintain. Keep them in sync.
 */

export type SessionState = "idle" | "running" | "stopped" | "error";

export type Role = "user" | "assistant" | "system" | "tool";

export interface SessionRecord {
	id: string;
	createdAt: string;
	updatedAt: string;
	state: SessionState;
	cwd: string;
	title?: string;
	model?: string;
	worker?: string;
	/** Set at merge time by `mewrite agents`; never persisted. */
	kind?: "hosted" | "interactive";
	/** OS pid for a live interactive session (from the liveness registry); never persisted. */
	pid?: number;
}

export interface MessageRecord {
	id: string;
	sessionId: string;
	role: Role;
	text: string;
	createdAt: string;
}

export interface Transcript {
	sessionId: string;
	messages: MessageRecord[];
}

export interface FileTreeEntry {
	name: string;
	path: string;
	type: "file" | "directory";
	size?: number;
}

export interface FileTreeResponse {
	sessionId: string;
	path: string;
	entries: FileTreeEntry[];
}

export interface FsListResponse {
	path: string;
	parent: string | null;
	home: string;
	entries: FileTreeEntry[];
}

export interface ReadFileResponse {
	sessionId: string;
	path: string;
	text: string;
	size: number;
	mtimeMs: number;
	encoding: "utf8";
}

export interface WriteFileRequest {
	path: string;
	text: string;
	expectedMtimeMs: number;
	expectedSize: number;
}

export interface WriteFileResponse {
	sessionId: string;
	path: string;
	size: number;
	mtimeMs: number;
	encoding: "utf8";
}

export interface CreateSessionRequest {
	cwd?: string;
	title?: string;
	model?: string;
	worker?: string;
}

export interface SendMessageRequest {
	text: string;
	worker?: string;
}

export type RunnerKind = "echo" | "agent";

export interface HealthCapabilities {
	runnerKind: RunnerKind;
	approvalSupported: boolean;
	/**
	 * Server streams the Phase 5c rich events: typed tool events (toolCallId/args/
	 * result), `usage` notifications, `stopReason` on state, and accepts the
	 * `set_thinking` RPC. Lets clients feature-detect before rendering meters.
	 */
	richEvents?: boolean;
}

export interface Health {
	ok: true;
	version: string;
	uptimeSec: number;
	capabilities: HealthCapabilities;
}

export interface WorkerRecord {
	name: string;
	url: string;
	token?: string;
	registeredAt: string;
	lastSeenAt?: string;
	labels?: Record<string, string>;
}

export interface RegisterWorkerRequest {
	name: string;
	url: string;
	token?: string;
	labels?: Record<string, string>;
}

export type ApprovalDecision = "once" | "session" | "deny";

export interface ApprovalParams {
	sessionId: string;
	approvalId: string;
	toolName: string;
	args: unknown;
	tier: string;
}

export interface ApprovalDecisionParams {
	approvalId: string;
	decision: ApprovalDecision;
}

// ---- JSON-RPC 2.0 over WebSocket ----
//
// Notifications (server → client):
//   { jsonrpc: "2.0", method: "token", params: { sessionId, text, role } }
//   { jsonrpc: "2.0", method: "tool",     params: { sessionId, name, status } }
//   { jsonrpc: "2.0", method: "state",    params: { sessionId, state } }
//   { jsonrpc: "2.0", method: "approval", params: { sessionId, approvalId, toolName, args, tier } }
//   { jsonrpc: "2.0", method: "file",     params: { sessionId, path, at } }
//   { jsonrpc: "2.0", method: "done",     params: { sessionId } }
//
// Requests (client → server):
//   { jsonrpc: "2.0", id: 1, method: "send",              params: { text } }
//   { jsonrpc: "2.0", id: 2, method: "interrupt",         params: {} }
//   { jsonrpc: "2.0", id: 3, method: "approval_decision", params: { approvalId, decision } }

export type RpcId = string | number;

export interface RpcRequest<P = unknown> {
	jsonrpc: "2.0";
	id: RpcId;
	method: string;
	params?: P;
}

export interface RpcNotification<P = unknown> {
	jsonrpc: "2.0";
	method: string;
	params?: P;
}

export interface RpcResponse<R = unknown> {
	jsonrpc: "2.0";
	id: RpcId;
	result?: R;
	error?: { code: number; message: string; data?: unknown };
}

export type RpcEnvelope = RpcRequest | RpcNotification | RpcResponse;

export interface TokenParams {
	sessionId: string;
	text: string;
	role: Role;
}

export interface ToolParams {
	sessionId: string;
	name: string;
	status: "start" | "ok" | "err";
	/** Correlates start↔end (5c). Present when the runner emits rich events. */
	toolCallId?: string;
	/** Tool call arguments, present on `status:"start"`. May be truncated over the wire. */
	args?: unknown;
	/** Tool result, present on `status:"ok"|"err"`. May be truncated over the wire. */
	result?: unknown;
	/** Mirrors status==="err"; kept explicit so clients don't re-derive it. */
	isError?: boolean;
}

export type StopReason = "stop" | "max_tokens" | "error" | "aborted";

export interface UsageParams {
	sessionId: string;
	/** Estimated context tokens, or null if unknown (e.g. right after compaction). */
	tokens: number | null;
	contextWindow: number;
	/** Context usage percentage, or null if tokens is unknown. */
	percent: number | null;
	thinkingLevel: string;
}

export interface StateParams {
	sessionId: string;
	state: SessionState;
	/** Why the turn ended, populated on the terminal state of a turn (5c). */
	stopReason?: StopReason;
}

export interface SetThinkingParams {
	level: string;
}

export interface DoneParams {
	sessionId: string;
}

export interface FileChangedParams {
	sessionId: string;
	/** Path relative to the session cwd (POSIX-style, no leading slash). */
	path: string;
	/** Epoch millis when the mutation completed. */
	at: number;
}

export interface SendParams {
	text: string;
}

export const DEFAULT_DAEMON_PORT = 7421;
export const DEFAULT_DAEMON_HOST = "127.0.0.1";

/** Minimum interval between coalesced token batches sent to clients. ~16 ms. */
export const TOKEN_TICK_MS = 16;
